### ISSUE TITLE
что из себя представляет бот

### ISSUE THREAD

**Issue by LilBtr** [we1come32/funbetbot#1]
можно подробно что это за бот (очень подробно)

**Comment by LilBtr** [comment]
у меня нет возможности проверять в ближайшие месяцы, вот причина вопроса

**Comment by we1come32** [comment]
Бот для ставок на реальные события в телеграме

Позволяет превратить ставки на деньги у букмекеров на реальные события в рейтинговую игру с виртуальными очками без финансовых вложений. Баланс при достижении критической точки можно пополнить на 500 очков
Парсит игры и коэффициенты реальных событий от букмекеров
Идеально подходит для людей, кто хочет избавиться от лудомании

В данный момент разработка не продолжается из-за отсутствия желания его развивать. Присутствуют определенные проблемы со стабильностью обхода блокировок со стороны букмекеров
